# Thanks to custity of https://gist.github.com/jreese/6207161

before_install:
#    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo add-apt-repository --yes ppa:beineri/opt-qt55
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt55-qmake
script:
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make
